/**
 * Auto-generated module map for component discovery
 * This file is generated by the build process and maps component paths to their dynamic imports
 * 
 * Usage: Update this file when adding new component mockups
 */

export const modules: Record<string, () => Promise<Record<string, unknown>>> = {
  // Add component imports here as they are created
  // Example:
  // './components/mockups/Button.tsx': () => import('../components/mockups/Button.tsx'),
};
